### ISSUE TITLE
Npm install fails on Ubuntu

### ISSUE THREAD

**Issue by clicman** [AppraiseQA/appraise#2]
Installing from root via  `npm install appraise -g`

![image](https://user-images.githubusercontent.com/1079535/32643998-71dfb146-c611-11e7-883d-14b0d4462e7d.png)

**Comment by gojko** [comment]
what node/npm version? looks perhaps as a problem with one of the dependencies (puppeteer)

**Comment by przemyslawjanpietrzak** [comment]
"EACCES: permission denied...." yor user has no access to /usr/lib/node_modules.
Try `sudo npm install appraise -g` or install appraise locally.

**Comment by gojko** [comment]
closing due to lack of response. if you still have this issue, please re-open it and provide additional info.
