### ISSUE TITLE
Ability to run examples only on a specific OS

### ISSUE THREAD

**Issue by onatm** [AppraiseQA/appraise#3]
Is there any way to run examples only on a specific OS?

We are having an issue with `Roboto` font - The font is rendered slightly different on Windows and Mac OS X and we want to approve our examples separately on different platforms.

**Comment by gojko** [comment]
you can use `--page <page name>`  to run only examples from a particular page, so eg create osx page and linux page for rendering differences. you can also use `--tolerance` to ignore small differences
