### ISSUE TITLE
React Support?

### ISSUE THREAD

**Issue by leotorres-16** [AppraiseQA/appraise#5]
Hello, I think this is a great idea and wanted to know if there is any planned or way of making it work with React? it could render React components and then the snapshot maybe?

**Comment by gojko** [comment]
you should be able to do this already by using the [beforeScreenshot](https://github.com/AppraiseQA/appraise/blob/master/examples/before-screenshot.md) function. You can kick off a javascript process or wait for a custom event to know when to take a screenshot using that part of the fixture. I don't use react so I do not have a ready made example, sorry.
