### ISSUE TITLE
URL test issue

### ISSUE THREAD

**Issue by leotorres-16** [AppraiseQA/appraise#6]
Hi, I am just exploring this a little bit, and I wanted to take the image from a URL, however the Actual image is completely different from the Source and I don't understand why. Another issue I have seen is when you take an image using an URL you can see that the screenshots are a bit distorted (You can use google as an example) and every time you run the test it finds a difference.

**Comment by gojko** [comment]
the difference might be due to a number of factors, eg screen resolution, how the target system handles headless browsers etc. i find this kind of tooling most useful when you can control the other end, so you know what parameters to set when testing.

regarding distortions, i'm not sure what you mean by that. can you post an example?

**Comment by leotorres-16** [comment]
You are right, this works better when you actually use the html, I am using Gatsby JS to create static website, however when I render my html it renders in a mobile kind of view, you know why this might be happening?

With GatsbyJS is easy to make it work, you just need to build your static website and then read the generated html with node:

```
var fs = require('fs');
var file = fs.readFileSync("path/to/your/file.html", "utf8");
module.exports = function (params) {
	return {
		contentType: 'text/html',
		content: `${file}`
	};
};
```

**Comment by leotorres-16** [comment]
I know the above mobile issue might be related to my styles, they are done using styled components using a library called emotion for React

**Comment by gojko** [comment]
check out how to set the initial size and the clip region here (see the part on managing responsive pages) https://github.com/AppraiseQA/appraise/blob/master/examples/controlling-screenshots.md

**Comment by leotorres-16** [comment]
Thanks, where do we set this on the .md file? also is it expected to render on mobile as a default?

**Comment by gojko** [comment]
you can set it the command line (applies to the whole test run), in the header of the file (applies to all examples in a .md file), or on each example (example values override header values). check out https://github.com/AppraiseQA/appraise/blob/master/docs/run.md for more information, and to see the defaults
