### ISSUE TITLE
Q: Running tests on specific elements on a remote web server

### ISSUE THREAD

**Issue by bm-stschneider** [AppraiseQA/appraise#7]
Is it possible to have appraise target a dom element on a remote website to test against? And if so, how would I set up appraise to let it know where to navigate and what to take a screenshot of?

**Comment by gojko** [comment]
you can return an object from the fixture, with a `url` to the remote website. You can also send code in `beforeScreenshot` that would tell it what to focus on. the code will execute in the context of the remote page, for example removing all the other elements etc. Alternatively, you can provide `clip-x`/`clip-y` and so on to clip a particular region. 

check out https://github.com/AppraiseQA/appraise/blob/master/examples/controlling-screenshots.md and https://github.com/AppraiseQA/appraise/blob/master/examples/before-screenshot.md

**Comment by bm-stschneider** [comment]
How would I tell it on what to focus on?

**Comment by gojko** [comment]
appraise doesn't have any specific features for focus, but you can use the normal DOM features for focusing in `beforeScreenshot`. Don't return just a string with a URL, but return an object that has that URL in the `url` field, and a `beforeScreenshot` function.
