### ISSUE TITLE
can diff with a part of the page?

### ISSUE THREAD

**Issue by qileilove** [AppraiseQA/appraise#8]
something like i just want to diff header or footer in one page, use the css selector to choose which part i wanted?

**Comment by gojko** [comment]
you can set a clip region when doing the screenshot, so you can include only the header if you like

**Comment by qileilove** [comment]
thats not what i wanted, i know the appraise use the puppeteer to do some action(like navigator to url),can we add new feature for it? like this https://github.com/GoogleChrome/puppeteer/pull/452/files
